SPRINGBOOT+DDD 的微服务环境,值得参考一下

造轮子的其他意见:
为什么我们要去造轮子？

造轮子的核心目的，是为了解决通用共性问题的凝练和复用。

虽然市面上已经有了大量成熟稳定用于支撑系统建设的轮子，也就是服务、框架、组件、工具等，但对于一些较大型的公司来说，这些轮子可能并不一定能很好的支撑起系统需要承载的服务体量，这个时候就需要自建一些轮子。

而提倡的不重复造轮子，新造轮子不一定能保证稳定性。一般用在以官网推出的核心轮子上是适合的，比如 SpringBoot、Netty、HBase 等。但对于一些特殊场景的解决方案工具型组件，通常是没有完全符合的轮子的，就像 SpringBoot 脚手架。

其实每个较大型的公司都会有很多同类技术服务的组件，例如 RPC、数据库路由、注册中心、分布式任务、MQ队列消息等，而这时候脚手架的开发就需要适配这些组件，搭建出符合自己公司技术栈实现需要的系统架构。这不同于一些较小的互联网公司，可以完全使用 SpringBoot 提供的一整套解决方案

另外，造轮子是个人技术沉淀、也是薪资待遇的积累！别说造不了飞机，只是你没有提供场地！

有什么场景还能造轮子？



用于架构基建下的所有模块都可以成为轮子，通常我们都是在这些场景下：负载均衡、服务网关、服务治理、框架语言、服务组件、数据承载、框架结构、部署方式、工具插件，建设需要的轮子。

其实一个较成熟的互联网公司，大部分场景下的轮子，已基本建造完了。剩下的一般是用于解决业务场景下非业务逻辑的通用性组件，例如，高并发下的缓存热Key、Redis 层路由、活动邀请的不唯一短码生成，等等类似这样的场景。但此类场景的轮子建设也是非常有价值的，在公司层面使用稳定后，还可以推广到市场获得一定的认可，以及更好的会被收入到 Apache 项目。
————————————————
版权声明：本文为CSDN博主「小傅哥」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/generalfu/article/details/114817914

= start.spring.io image:https://badges.gitter.im/spring-io/initializr.svg[link="https://gitter.im/spring-io/initializr?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
:library: https://github.com/spring-io/initializr

This repository configures a {library}[Spring Initializr] instance with a custom UI
running at https://start.spring.io. The following modules are available:

* `start-client`: client-side assets
* `start-site`: server infrastructure and metadata configuration
* `start-site-verification`: tests to verify the validity of the metadata

[[using]]
== Using
There is a link:USING.adoc[dedicated page] that describes how you can interact with the
service.



[[build]]
== Building from Source

You need Java 11 and a bash-like shell.

[[building]]
=== Building

Invoke the build at the root of the project

[indent=0]
----
    $ ./mvnw clean install
----

The project also includes a number of longer-running verification tests. They
can be built and run using the `verification` profile:

[indent=0]
----
    $ ./mvnw -Pverification clean install
----

The project's other tests are not included in the `verification` profile. All of
the project's tests can be run using the `full` profile:

[indent=0]
----
    $ ./mvnw -Pfull clean install
----

If building `start-client` fails, you may have an outdated cache that can be deleted as
follows:

[indent=0]
----
    $ cd start-client
    $ rm -rf .cache node_modules
----



[[run-app]]
=== Running the app locally
As long as you've built the project beforehand (in particular `start-client`), you can
easily start the app as any other Spring Boot app:

[indent=0]
----
    $ cd start-site
    $ ../mvnw spring-boot:run
----

[[run-ide]]
=== Running the app in an IDE
You should be able to import the project into your IDE with no problems. Once there you
can run the `StartApplication` from its main method and debug it. If you also need to
work on the library, adding the `initializr` project in your workspace would make sure
to reload the app whenever you make any change.

This is the recommended way to operate while you are developing the application,
especially the UI.

== Reusing the Web UI
This instance has a thin layer with our opinions about getting started with Spring Boot.
You can reuse them but please keep in mind that this is not supported with the same
level as the Spring Initializr library. The Web UI, in particular, is for our own
purpose and is not particularly engineered to be easily extended.



== Deploying to Cloud Foundry

If you are on a Mac and using https://brew.sh/[homebrew], install the Cloud Foundry
CLI:

[indent=0]
----
    $ brew install cloudfoundry-cli
----

Alternatively, download a suitable binary for your platform from
https://console.run.pivotal.io/tools[Pivotal Web Services].

You should ensure that the application name and URL (name and host values) are
suitable for your environment before running `cf push`.

First, make sure that you have <<building, built the application>>, then make sure first
that the jar has been created:

[indent=0]
----
    $ cd start-site
    $ ../mvnw package
----

The project creates a regular library jar and a repackaged archive that can be used to
start the application with the `exec` classifier. Once the build as completed, you can
push the application:

[indent=0]
----
    $ cf push your-start -p target/start-site-exec.jar
----


== License
The start.spring.io website is Open Source software released under the
https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
